### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'  (newer hub version incompatible..)

### ISSUE THREAD

**Issue by alandalsong** [D-Ogi/WatermarkRemover-AI#6]
python remwmgui.py

Traceback (most recent call last):
  File "/content/WatermarkRemover-AI/remwmgui.py", line 10, in <module>
    import remwm  # Ensure remwm.py is in the same directory or in the PYTHONPATH
  File "/content/WatermarkRemover-AI/remwm.py", line 7, in <module>
    from lama_cleaner.model_manager import ModelManager
  File "/usr/local/lib/python3.10/dist-packages/lama_cleaner/model_manager.py", line 8, in <module>
    from lama_cleaner.model.controlnet import ControlNet
  File "/usr/local/lib/python3.10/dist-packages/lama_cleaner/model/controlnet.py", line 7, in <module>
    from diffusers import ControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 29, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

**Comment by mambajoe** [comment]
got same error

**Comment by D-Ogi** [comment]
Sorry to hear that. The dependencies got newer versions which aren't backwards compatible. Could you please also check is the gui version of this script works for you? If time allows I will create a the miniconda-based installer to prevent such issues in the future.

**Comment by mambajoe** [comment]
indeed, we would need to downgrade the library or apply the following change
<img width="883" alt="381035560-bf43b7e1-d176-4cff-8790-c9250dd36cf9" src="https://github.com/user-attachments/assets/1222f10b-b821-44fa-a862-2ac4ba85c5d9" />

**Comment by bookamp** [comment]
downgrading to an earlier version of huggingface_hub did the trick for me.

pip install -Iv huggingface_hub==0.25.1

**Comment by D-Ogi** [comment]
Hi @alandalsong, @mambajoe, and @bookamp,

Thanks for reporting this issue and for your patience. I’ve implemented a Conda-based setup to address dependency compatibility problems like this. The new setup ensures that the required versions of libraries are installed in an isolated environment, preventing such conflicts.

You can now pull the latest changes and set up the environment as follows:
1. Pull the updated code:
   ```bash
   git pull origin main
   ```
2. Run the setup script:
   ```bash
   bash setup.sh
   ```

This will create a Conda environment with all dependencies properly configured. A big thanks to @crosstyan (https://github.com/crosstyan/WatermarkRemover-AI) for the forked version that inspired and streamlined this solution!

Let me know if the issue persists or if you encounter anything else. Your feedback is always appreciated.
